### ISSUE TITLE
Missing geolocation

### ISSUE THREAD

**Issue by axelolsson** [ulander-a/simply_weather#1]
- [ ] Kunna se temperatur och andra väderförhållanden för sin nuvarande position

**Comment by ulander-a** [comment]
Works locally now. Doesn't seem to work with Binero.

**Comment by axelolsson** [comment]
@ulander-a This is why: https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only

Not Binero related. But your implementation provides an input field as a fallback which is fine! Good job.
